export {default as TrashCan} from './trash-alt-solid.svg'
export {default as PenIcon} from './pen-square-solid.svg'
export {default as ArrowDown} from './arrow-circle-down-solid.svg'
export {default as ArrowUp} from './arrow-circle-up-solid.svg'
export {default as Plus} from './plus.svg'
export {default as Cross} from './times-circle-solid.svg'
export {default as ChevronUp} from './chevron-up-solid.svg'
export {default as ChevronDown} from './chevron-down-solid.svg'
