export {default as TrashCan} from './trash-alt-solid.svg'
export {default as PenIcon} from './pen-square-solid.svg'
export {default as ArrowDown} from './arrow-circle-down-solid.svg'
export {default as ArrowUp} from './arrow-circle-up-solid.svg'
export {default as Plus} from './plus.svg'
